### ISSUE TITLE
Exe file for mainly.py

### ISSUE THREAD

**Issue by pooja7909** [routayush1/HOTEL-MANGEMENT-GUI-AND-NORMAL-PROGRAM-PYTHON-#3]
@routayush1  have you tried to make exe file of your Python project. Does it work fine? I tried to create exe for mainly it worked fine but the additional python files are not working when I click the command buttons. IF you have done so please let me know.
Thanks

**Comment by routayush1** [comment]
NO, i have not made exe file of this repo &  I am currently not maintaining this project
